name: CI/CD - Build Docker, Push to GHCR and Update Site

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/mi-web-app
      SITE_INDEX: index.html

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update index.html with build info
        run: |
          echo "<!-- BUILD_INFO -->" > temp.txt
          echo "<p>Build: $(date -u +"%Y-%m-%dT%H:%M:%SZ") - SHA: ${{ github.sha }} - Image: ${{ env.IMAGE_NAME }}:${{ github.sha }}</p>" >> temp.txt
          echo "<!-- END_BUILD_INFO -->" >> temp.txt

          sed -i '/<!-- BUILD_INFO -->/,/<!-- END_BUILD_INFO -->/d' ${{ env.SITE_INDEX }}
          cat temp.txt >> ${{ env.SITE_INDEX }}
          rm temp.txt

      - name: Commit updated index.html
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ env.SITE_INDEX }}
          git commit -m "ci: update index with build info" || echo "No changes to commit"
          git push
